In [4]:
import numpy as np 
np.set_printoptions (suppress=True) 
import pandas as pd 
import warnings 
import matplotlib.pyplot as plt 
warnings.filterwarnings('ignore')

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier

In [6]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,classification_report
from sklearn.preprocessing import StandardScaler,MinMaxScaler

In [7]:
from sklearn.ensemble import RandomForestClassifier

In [8]:
rfc = RandomForestClassifier(n_estimators=150,
                             criterion='entropy',
                             random_state=42,
                             min_samples_split=4,
                             min_samples_leaf=3,
                             max_features="log2",
                             oob_score=True,
                             class_weight="balanced",
                             n_jobs=10,
                             )

In [31]:
rfc.fit(Xtrain,Ytrain)

RandomForestClassifier(class_weight='balanced', criterion='entropy',
                       max_features='log2', min_samples_leaf=3,
                       min_samples_split=4, n_estimators=150, n_jobs=10,
                       oob_score=True, random_state=42)

In [32]:
predicted_output=rfc.predict(Xtest)

In [33]:
print("********** Performance Evaluation of RF **********")
print(confusion_matrix(Ytest,predicted_output))
print(classification_report(Ytest,predicted_output))

********** Performance Evaluation of RF **********
[[6 1]
 [1 6]]
              precision    recall  f1-score   support

          No       0.86      0.86      0.86         7
         Yes       0.86      0.86      0.86         7

    accuracy                           0.86        14
   macro avg       0.86      0.86      0.86        14
weighted avg       0.86      0.86      0.86        14



In [34]:
predicted_output

array(['No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes',
       'No', 'Yes', 'Yes', 'No'], dtype=object)

In [25]:
ons=pd.read_csv('onssdb.csv', sep=',', header=0)
print(ons.head(10))

     Drug A Name Drug A Chemical Structure Drug B Name  \
0    Amoxicillin               C16H19N3O5S    Warfarin   
1  Ciprofloxacin               C17H18FN3O3  Tizanidine   
2     Furosemide             C12H11ClN2O5S     Digoxin   
3      Ibuprofen                  C13H18O2     Aspirin   
4   Methotrexate                C20H22N8O5  Probenecid   
5      Metformin                   C4H11N5  Cimetidine   
6       Naproxen                16C14H14O3     Lithium   
7     Paroxetine                C19H20FNO3   Tamoxifen   
8    Simvastatin                  C25H38O5   Verapamil   
9  Acetaminophen                   C8H9NO2  Loratadine   

  Drug B Chemical Structure Interaction  \
0                  C19H16O4         Yes   
1                   C9H8N5S         Yes   
2                 C41H64O14         Yes   
3                    C9H8O4         Yes   
4                C13H19NO4S         Yes   
5                 C10H16N6S         Yes   
6                     1s2s1         Yes   
7                

In [ ]:
ons.shape

(54, 6)

In [29]:
X=ons.iloc[:,0:4].values
Y=ons.iloc[:,4:5].values

In [30]:
Xtrain,Xtest,Ytrain,Ytest=train_test_split(X,Y,test_size=0.25,random_state=1)

In [ ]:
DT=DecisionTreeClassifier(random_state=0, criterion="entropy")

In [ ]:
DT.fit(Xtrain,Ytrain)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [ ]:
YDT=DT.predict(Xtest)

In [ ]:
print("********** Performance Evaluation of Decision Tree **********")
print(confusion_matrix(Ytest,YDT))
print(classification_report(Ytest,YDT))

********** Performance Evaluation of Decision Tree **********
[[5 2]
 [1 6]]
              precision    recall  f1-score   support

          No       0.83      0.71      0.77         7
         Yes       0.75      0.86      0.80         7

    accuracy                           0.79        14
   macro avg       0.79      0.79      0.78        14
weighted avg       0.79      0.79      0.78        14



In [ ]:
from sklearn.svm import SVC

In [ ]:
linear_svm = SVC(kernel='linear')
rbf_svm=SVC(kernel='rbf')
sigmoid_svm=SVC(kernel='sigmoid')
poly_svm=SVC(kernel='poly',degree=2)

In [ ]:
linear_svm.fit(Xtrain,Ytrain)
rbf_svm.fit(Xtrain,Ytrain)
sigmoid_svm.fit(Xtrain,Ytrain)
poly_svm.fit(Xtrain,Ytrain)

SVC(degree=2, kernel='poly')

In [ ]:
y_linear_svm=linear_svm.predict(Xtest)
y_rbf_svm=rbf_svm.predict(Xtest)
y_poly_svm=poly_svm.predict(Xtest)
y_sigmoid_svm=sigmoid_svm.predict(Xtest)

In [ ]:
print('******* Performance Evaluation of Linear SVM *******')
print(confusion_matrix(Ytest,y_linear_svm))
print(classification_report(Ytest,y_linear_svm))
print('******* Performance Evaluation of RBF SVM ********')
print(confusion_matrix(Ytest,y_rbf_svm))
print(classification_report(Ytest,y_rbf_svm))
print('******* Performance Evaluation of Sigmoid SVM ********')
print(confusion_matrix(Ytest,y_sigmoid_svm))
print(classification_report(Ytest,y_sigmoid_svm))
print('******* Performance Evaluation of Polynomial (2) SVM ********')
print(confusion_matrix(Ytest,y_poly_svm))
print(classification_report(Ytest,y_poly_svm))

******* Performance Evaluation of Linear SVM *******
[[7 0]
 [4 3]]
              precision    recall  f1-score   support

          No       0.64      1.00      0.78         7
         Yes       1.00      0.43      0.60         7

    accuracy                           0.71        14
   macro avg       0.82      0.71      0.69        14
weighted avg       0.82      0.71      0.69        14

******* Performance Evaluation of RBF SVM ********
[[7 0]
 [1 6]]
              precision    recall  f1-score   support

          No       0.88      1.00      0.93         7
         Yes       1.00      0.86      0.92         7

    accuracy                           0.93        14
   macro avg       0.94      0.93      0.93        14
weighted avg       0.94      0.93      0.93        14

******* Performance Evaluation of Sigmoid SVM ********
[[7 0]
 [7 0]]
              precision    recall  f1-score   support

          No       0.50      1.00      0.67         7
         Yes       0.00      0.00

In [ ]:

from sklearn.naive_bayes import GaussianNB

In [ ]:
gnb=GaussianNB()

In [ ]:
gnb.fit(Xtrain,Ytrain)

GaussianNB()

In [ ]:
y_nb=gnb.predict(Xtest)

In [ ]:
print('******* Performance Evaluation of Naive Bayes ********')
print(confusion_matrix(Ytest,y_nb))
print(classification_report(Ytest,y_nb))

******* Performance Evaluation of Naive Bayes ********
[[7 0]
 [4 3]]
              precision    recall  f1-score   support

          No       0.64      1.00      0.78         7
         Yes       1.00      0.43      0.60         7

    accuracy                           0.71        14
   macro avg       0.82      0.71      0.69        14
weighted avg       0.82      0.71      0.69        14



In [ ]:
ss=StandardScaler()
ss.fit(Xtrain)
Xtrain_norm=ss.transform(Xtrain)
Xtest_norm=ss.transform(Xtest)

In [26]:
from sklearn.preprocessing import LabelEncoder
cat_features = ["Drug A Name", "Drug A Chemical Structure", "Drug B Name", "Drug B Chemical Structure"]
for feature in cat_features:
    le = LabelEncoder()
    ons[feature] = le.fit_transform(ons[feature])

In [27]:
DA=ons["Drug A Name"]
MA=ons["Drug A Chemical Structure"]
DB=ons["Drug B Name"]
MB=ons["Drug B Chemical Structure"]

In [28]:
onss=pd.read_csv('onssdb.csv', sep=',', header=0)

In [18]:
def conn(a,b,c):
  j=0
  for i in onss[a]:
    if i == b:
      o=c[j]
      break
    j+=1
  return o

In [19]:
def MMM(a,b,c):
  j=0
  for i in onss[a]:
    if i == b:
      o=onss[c][j]
      break
    j+=1
  return o

In [35]:
import sklearn.preprocessing
m1 = input("Enter medication 1 : ")
mol1 = MMM("Drug A Name",m1,"Drug A Chemical Structure")
m2 = input("Enter medication 2 : ")
mol2 = MMM("Drug B Name",m2,"Drug B Chemical Structure")


# Define and fit transformers for non-numerical columns
converter_m1 = sklearn.preprocessing.LabelEncoder()
converter_m1.fit(ons["Drug A Name"])

converter_mol1 = sklearn.preprocessing.LabelEncoder()
converter_mol1.fit(ons["Drug A Chemical Structure"])

converter_m2 = sklearn.preprocessing.LabelEncoder()
converter_m2.fit(ons["Drug B Name"])

converter_mol2 = sklearn.preprocessing.LabelEncoder()
converter_mol2.fit(ons["Drug B Chemical Structure"])

# Encode user input
m1 = converter_m1.transform([conn("Drug A Name",m1,DA)])[0]
mol1 = converter_mol1.transform([conn("Drug A Chemical Structure",mol1,MA)])[0]
m2 = converter_m2.transform([conn("Drug B Name",m2,DB)])[0]
mol2 = converter_mol2.transform([conn("Drug B Chemical Structure",mol2,DB)])[0]
# Create input dictionary for the model
input_dict = {"Drug A Name": m1, "Drug A Chemical Structure": mol1, "Drug B Name": m2, "Drug B Chemical Structure": mol2}
input_df = pd.DataFrame(input_dict, index=[0])

# Predict the prohibited drug
result = rfc.predict(input_df)[0]

# Print drug recommendation
print("the result for your test :\n", result)

Enter medication 1 : Amoxicillin
Enter medication 2 : Warfarin
the result for your test :
 Yes


In [40]:
input_dict

{'Drug A Name': 2,
 'Drug A Chemical Structure': 8,
 'Drug B Name': 29,
 'Drug B Chemical Structure': 29}

In [ ]:
m1

2

In [39]:
X

array([[ 2,  8, 29, 11],
       [ 6, 10, 24, 28],
       [11,  1,  4, 24],
       [14,  3,  1, 29],
       [17, 16, 18,  5],
       [16, 23,  2,  2],
       [18,  0, 10,  0],
       [19, 13, 22, 20],
       [21, 20, 28, 21],
       [ 0, 25, 11, 15],
       [ 5, 22, 13,  6],
       [ 7, 15, 15,  8],
       [ 8,  7,  5,  9],
       [10, 18, 14, 22],
       [12, 26, 17, 26],
       [13, 24, 20, 17],
       [15,  6, 16, 12],
       [20,  9, 25,  3],
       [22, 17, 21, 14],
       [ 2,  8, 29, 11],
       [ 6, 10, 24, 28],
       [11,  1,  4, 24],
       [14,  3,  1, 29],
       [17, 16, 18,  5],
       [16, 23,  2,  2],
       [18,  4, 10,  0],
       [19, 13, 22, 20],
       [21, 20, 28, 21],
       [ 0, 25, 11, 15],
       [ 5, 22, 13,  6],
       [ 7, 15, 15,  8],
       [ 8,  7,  5,  9],
       [10, 19, 14, 22],
       [12, 26, 17, 26],
       [13, 24, 20, 17],
       [15,  6, 16, 12],
       [20,  9, 25,  3],
       [22, 17, 21, 14],
       [24, 12,  1, 29],
       [21, 20,  3, 23],


In [36]:
!pip install joblib

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [37]:
#Serialize the model and save
from joblib import dump, load
dump(rfc, 'module.pkl')
print("Random Forest Model Saved")
#Load the model
"""rfc = joblib.load('module.pkl')
# Save features from training
rnd_columns = list(X_train.columns)
joblib.dump(rnd_columns, 'rnd_columns.pkl')
print("Random Forest Model Colums Saved")"""

Random Forest Model Saved


'rfc = joblib.load(\'module.pkl\')\n# Save features from training\nrnd_columns = list(X_train.columns)\njoblib.dump(rnd_columns, \'rnd_columns.pkl\')\nprint("Random Forest Model Colums Saved")'

In [1]:
!pip install pickle5

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.1/132.1 kB 2.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for pickle5: filename=pickle5-0.0.11-cp310-cp310-linux_x86_64.whl size=256423 sha256=62e197a4d19e4a37a6c449c6854899c26a7612ebdca8907b45939a500dd23695
  Stored in directory: /root/.cache/pip/wheels/7d/14/ef/4aab19d27fa8e58772be5c71c16add0426acf9e1f64353235c
Successfully built pickle5


In [38]:
import pickle
filename = 'model2.sav'
pickle.dump(rfc, open(filename, 'wb'))